CREATE TABLE public.serverdata (
	"timestamp" int4 NOT NULL,
	vm2_cpu_avg float8 NULL,
	vm2_cpu_max float8 NULL,
	vm2_memory text NULL,
	vm2_net_rx_total float8 NULL,
	vm2_net_tx_total float8 NULL,
	vm2_disk_iops_total float8 NULL,
	vm2_disk_throughput_total float8 NULL,
	vm2_disk_latency_avg float8 NULL,
	vm3_cpu_avg float8 NULL,
	vm3_cpu_max float8 NULL,
	vm3_memory text NULL,
	vm3_net_rx_total float8 NULL,
	vm3_net_tx_total float8 NULL,
	vm3_disk_iops_total float8 NULL,
	vm3_disk_throughput_total float8 NULL,
	vm3_disk_latency_avg float8 NULL,
	vm4_cpu_avg float8 NULL,
	vm4_cpu_max float8 NULL,
	vm4_memory text NULL,
	vm4_net_rx_total float8 NULL,
	vm4_net_tx_total float8 NULL,
	vm4_disk_iops_total float8 NULL,
	vm4_disk_throughput_total float8 NULL,
	vm4_disk_latency_avg float8 NULL,
	vm5_cpu_avg float8 NULL,
	vm5_cpu_max float8 NULL,
	vm5_memory text NULL,
	vm5_net_rx_total float8 NULL,
	vm5_net_tx_total float8 NULL,
	vm5_disk_iops_total float8 NULL,
	vm5_disk_throughput_total float8 NULL,
	vm5_disk_latency_avg float8 NULL,
	CONSTRAINT serverdata_pkey PRIMARY KEY ("timestamp")
);